// client-v2/src/routes/laporan-warga/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { pb } from '$lib/pb';
	import { isPengurus, isScurity } from '$lib/auth';
	import { toast } from '$lib/ui';
	import type { Lapor, LaporStatus, Warga } from '$lib/types';
	import { getMyWarga } from '$lib/dashboard';
	import {
		listLaporWarga,
		filterLaporForRole,
		updateLapor,
		laporFotoUrl
	} from '$lib/lapor';
	import Modal from '$lib/components/Modal.svelte';
	import States from '$lib/components/States.svelte';

	let list = $state<Lapor[]>([]);
	let loading = $state(true);
	let error = $state('');
	let me = $state<Warga | null>(null);
	let preview = $state<string | null>(null);

	// Edit modal
	let editing = $state<Lapor | null>(null);
	let editStatus = $state<LaporStatus>('Menunggu Konfirmasi');
	let editRespons = $state('');
	let saving = $state(false);

	const STATUS_OPTS: LaporStatus[] = [
		'Menunggu Konfirmasi',
		'Diproses',
		'Selesai',
		'Ditolak'
	];

	onMount(async () => {
		// Scurity tidak boleh masuk halaman ini
		if ($isScurity) {
			goto('/dashboard', { replaceState: true });
			return;
		}
		await load();
	});

	async function load() {
		loading = true;
		error = '';
		try {
			const uid = pb.authStore.record?.id;
			if (uid) {
				try {
					me = await getMyWarga(uid);
					if (me.pengurus) isPengurus.set(true);
				} catch (e) {
					console.warn('warga not found:', e);
				}
			}
			const raw = await listLaporWarga();
			list = filterLaporForRole(raw, me);
		} catch (e) {
			error = e instanceof Error ? e.message : 'Gagal memuat laporan.';
		} finally {
			loading = false;
		}
	}

	function openEdit(l: Lapor) {
		editing = l;
		editStatus = l.status || 'Menunggu Konfirmasi';
		editRespons = l.respons || '';
	}

	async function saveEdit() {
		if (!editing) return;
		saving = true;
		try {
			const rec = await updateLapor(editing.id, {
				status: editStatus,
				respons: editRespons
			});
			list = list.map((it) =>
				it.id === editing!.id ? { ...it, ...rec, expand: it.expand } : it
			);
			editing = null;
			toast('Laporan berhasil diperbarui', 'ok');
		} catch (e) {
			toast(e instanceof Error ? e.message : 'Gagal memperbarui laporan.', 'err');
		} finally {
			saving = false;
		}
	}

	function statusConf(s?: string): { bg: string; color: string; icon: string } {
		if (s === 'Selesai')
			return { bg: '#E8F5EE', color: '#15935A', icon: '✓' };
		if (s === 'Diproses')
			return { bg: '#FBF1DD', color: '#C8821A', icon: '⟳' };
		if (s === 'Ditolak')
			return { bg: '#FBE9E9', color: '#C24A4A', icon: '✕' };
		return { bg: '#EEF1EF', color: '#8A9991', icon: '○' };
	}

	function borderColor(s?: string): string {
		if (s === 'Selesai') return '#15935A';
		if (s === 'Ditolak') return '#C24A4A';
		return '#C8821A';
	}

	function fmtDate(v?: string): string {
		if (!v) return '—';
		return new Date(v).toLocaleDateString('id-ID', {
			day: 'numeric',
			month: 'short',
			year: 'numeric'
		});
	}

	const editConf = $derived(editing ? statusConf(editing.status) : null);

	// Stats
	const stats = $derived({
		total: list.length,
		selesai: list.filter((l) => l.status === 'Selesai').length,
		proses: list.filter(
			(l) => l.status === 'Diproses' || !l.status || l.status === 'Menunggu Konfirmasi'
		).length
	});
</script>

<!-- Green header -->
<header class="hd">
	<div class="hd-row">
		<div>
			<div class="lbl">Warga P2S</div>
			<h1>Laporan Warga</h1>
		</div>
		<button class="back-btn" onclick={() => history.back()}>← Kembali</button>
	</div>
</header>

<div class="page-body">
	{#if list.length > 0}
		<div class="stats">
			<div class="stat">
				<div class="v" style="color: var(--c-text)">{stats.total}</div>
				<div class="k">Total</div>
			</div>
			<div class="stat ok">
				<div class="v" style="color: var(--c-primary)">{stats.selesai}</div>
				<div class="k">Selesai</div>
			</div>
			<div class="stat warn">
				<div class="v" style="color: #C8821A">{stats.proses}</div>
				<div class="k">Diproses</div>
			</div>
		</div>
	{/if}

	{#if !$isPengurus && list.length > 0}
		<div class="notice">
			<svg width="16" height="16" viewBox="0 0 24 24" fill="none">
				<circle cx="12" cy="12" r="9" stroke="#C8821A" stroke-width="1.8" />
				<path d="M12 7v6" stroke="#C8821A" stroke-width="1.8" stroke-linecap="round" />
				<circle cx="12" cy="16" r="1" fill="#C8821A" />
			</svg>
			<span>Laporan menunggu konfirmasi hanya terlihat oleh pengurus dan pelapor.</span>
		</div>
	{/if}

	{#if loading}
		<States kind="loading" rows={5} />
	{:else if error}
		<States kind="error" text={error} onRetry={load} />
	{:else if list.length === 0}
		<States
			kind="empty"
			title="Belum ada laporan"
			text={$isPengurus
				? 'Warga belum mengirim laporan apapun.'
				: 'Belum ada laporan yang tersedia.'}
		/>
	{:else}
		<div class="items">
			{#each list as it (it.id)}
				{@const conf = statusConf(it.status)}
				<div class="item card" style="border-left-color: {borderColor(it.status)}">
					<div class="row">
						{#if it.foto}
							<button
								class="thumb"
								onclick={() => (preview = laporFotoUrl(it))}
								aria-label="Preview foto"
							>
								<img
									src={laporFotoUrl(it, '160x160')}
									alt="Foto laporan"
									loading="lazy"
								/>
							</button>
						{/if}
						<div class="body">
							<div class="who">
								<span class="who-name">
									{it.expand?.warga?.expand?.user?.name || 'Warga'}
								</span>
								<span class="who-sub">
									· No. {it.expand?.warga?.no_rumah || '-'}
								</span>
							</div>
							<p class="ket">{it.keterangan || '-'}</p>
							<div class="foot">
								<span
									class="chip stat-chip"
									style="background:{conf.bg}; color:{conf.color}"
								>
									<span class="ico">{conf.icon}</span>
									{it.status || 'Menunggu'}
								</span>
								<span class="date">{fmtDate(it.created)}</span>
							</div>
							{#if it.respons}
								<div class="respons">
									<div class="respons-lbl">Tanggapan Pengurus</div>
									<div class="respons-txt">{it.respons}</div>
								</div>
							{/if}
							{#if $isPengurus}
								<button class="edit-btn" onclick={() => openEdit(it)}>
									<svg width="14" height="14" viewBox="0 0 14 14" fill="none">
										<path
											d="M10 1.5L12.5 4L4.5 12H2V9.5L10 1.5Z"
											stroke="currentColor"
											stroke-width="1.5"
											stroke-linecap="round"
											stroke-linejoin="round"
										/>
									</svg>
									Edit / Tanggapi
								</button>
							{/if}
						</div>
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>

<!-- ═══ Preview foto full-screen ═══ -->
{#if preview}
	<div
		class="preview-back"
		role="dialog"
		aria-modal="true"
		aria-label="Preview foto laporan"
		tabindex="-1"
		onclick={(e) => {
			if (e.target === e.currentTarget) preview = null;
		}}
		onkeydown={(e) => {
			if (e.key === 'Escape') preview = null;
		}}
	>
		<button
			class="preview-close"
			onclick={() => (preview = null)}
			aria-label="Tutup"
		>
			✕
		</button>
		<img src={preview} alt="Preview" />
	</div>
{/if}

<!-- ═══ Modal edit ═══ -->
<Modal
	open={editing !== null}
	title="Edit Laporan"
	onClose={() => (editing = null)}
	maxWidth={460}
>
	{#if editing}
		<div class="edit-warga">
			<div class="ew-badge">
				{(editing.expand?.warga?.no_rumah || '?').slice(-2)}
			</div>
			<div class="ew-mid">
				<div class="ew-name">
					{editing.expand?.warga?.expand?.user?.name || 'Warga'}
				</div>
				<div class="ew-sub">
					No. {editing.expand?.warga?.no_rumah || '-'}
				</div>
			</div>
			{#if editConf}
				<span
					class="chip stat-chip"
					style="background:{editConf.bg}; color:{editConf.color}"
				>
					<span class="ico">{editConf.icon}</span>
					{editing.status || 'Menunggu'}
				</span>
			{/if}
		</div>

		<div class="f-label" style="margin-top: 4px">Status Laporan</div>
		<div class="status-pills">
			{#each STATUS_OPTS as s (s)}
				<button
					class="s-pill"
					class:on={editStatus === s}
					onclick={() => (editStatus = s)}
				>
					{s === 'Menunggu Konfirmasi' ? 'Menunggu' : s}
				</button>
			{/each}
		</div>

		<label class="f-label" for="respons-input" style="margin-top: 16px">
			Tanggapan <span class="opt">(opsional)</span>
		</label>
		<textarea
			id="respons-input"
			class="f-textarea"
			bind:value={editRespons}
			placeholder="Tulis tanggapan untuk warga…"
			rows="3"
		></textarea>

		<div class="modal-actions" style="margin-top: 18px">
			<button
				class="btn btn-outline"
				onclick={() => (editing = null)}
				disabled={saving}
			>
				Batal
			</button>
			<button class="btn btn-primary" onclick={saveEdit} disabled={saving}>
				{saving ? 'Menyimpan…' : 'Simpan Perubahan'}
			</button>
		</div>
	{/if}
</Modal>

<style>
	/* ── Header ── */
	.hd {
		background: var(--c-primary-gradient);
		padding: 22px 18px 40px;
		border-bottom-left-radius: 28px;
		border-bottom-right-radius: 28px;
	}

	.hd-row {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 12px;
	}

	.lbl {
		color: rgba(255, 255, 255, 0.7);
		font-size: 14px;
		font-weight: 500;
	}

	h1 {
		color: #fff;
		font-size: 20px;
		font-weight: 800;
		letter-spacing: -0.02em;
		margin-top: 2px;
	}

	.back-btn {
		background: rgba(255, 255, 255, 0.15);
		border: 1px solid rgba(255, 255, 255, 0.2);
		color: #fff;
		padding: 8px 16px;
		border-radius: 20px;
		font-size: 13px;
		font-weight: 600;
		backdrop-filter: blur(4px);
	}

	.page-body {
		padding: 20px 20px 40px;
		margin-top: -24px;
	}

	/* ── Stats ── */
	.stats {
		display: flex;
		gap: 8px;
		margin-bottom: 16px;
	}

	.stat {
		flex: 1;
		background: #eff1f0;
		border-radius: 14px;
		padding: 12px 10px;
		text-align: center;
	}

	.stat.ok {
		background: #e8f5ee;
	}

	.stat.warn {
		background: #fbf1dd;
	}

	.stat .v {
		font-size: 22px;
		font-weight: 800;
		line-height: 1.2;
	}

	.stat .k {
		font-size: 11px;
		font-weight: 600;
		color: var(--c-text-muted);
		margin-top: 2px;
	}

	/* ── Notice ── */
	.notice {
		display: flex;
		align-items: center;
		gap: 8px;
		background: #fbf1dd;
		border-radius: 12px;
		padding: 10px 14px;
		margin-bottom: 16px;
		font-size: 12px;
		color: #7a5a14;
		line-height: 1.4;
	}

	/* ── Items ── */
	.items {
		display: flex;
		flex-direction: column;
		gap: 12px;
	}

	.item {
		padding: 16px;
		border-left: 4px solid var(--c-border);
	}

	.row {
		display: flex;
		gap: 12px;
	}

	.thumb {
		border: 1px solid #eff1f0;
		border-radius: 12px;
		padding: 0;
		background: none;
		cursor: pointer;
		width: 72px;
		height: 72px;
		flex-shrink: 0;
		overflow: hidden;
	}

	.thumb img {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}

	.body {
		flex: 1;
		min-width: 0;
	}

	.who {
		display: flex;
		gap: 6px;
		align-items: center;
		flex-wrap: wrap;
		margin-bottom: 4px;
	}

	.who-name {
		font-size: 13px;
		font-weight: 700;
		color: var(--c-text);
	}

	.who-sub {
		font-size: 12px;
		color: var(--c-text-light);
		font-weight: 500;
	}

	.ket {
		font-size: 13px;
		color: #475569;
		line-height: 1.45;
		margin-bottom: 8px;
		display: -webkit-box;
		-webkit-line-clamp: 3;
		line-clamp: 3;
		-webkit-box-orient: vertical;
		overflow: hidden;
	}

	.foot {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
		flex-wrap: wrap;
	}

	.stat-chip {
		display: inline-flex;
		align-items: center;
		gap: 5px;
		padding: 4px 10px;
		border-radius: 20px;
		font-size: 11px;
		font-weight: 700;
	}

	.stat-chip .ico {
		font-size: 13px;
		line-height: 1;
	}

	.date {
		font-size: 11px;
		color: var(--c-text-light);
		white-space: nowrap;
	}

	.respons {
		margin-top: 10px;
		padding: 10px 12px;
		background: #f8fafc;
		border-radius: 10px;
		border-left: 3px solid var(--c-primary);
	}

	.respons-lbl {
		font-size: 10px;
		font-weight: 700;
		color: var(--c-primary);
		text-transform: uppercase;
		letter-spacing: 0.04em;
		margin-bottom: 3px;
	}

	.respons-txt {
		font-size: 12px;
		color: #475569;
		line-height: 1.45;
	}

	.edit-btn {
		margin-top: 10px;
		display: inline-flex;
		align-items: center;
		gap: 6px;
		padding: 8px 14px;
		background: #eff1f0;
		color: var(--c-text);
		border: none;
		border-radius: 10px;
		font-size: 12px;
		font-weight: 700;
		font-family: inherit;
	}

	/* ── Preview overlay ── */
	.preview-back {
		position: fixed;
		inset: 0;
		z-index: 9999;
		background: rgba(0, 0, 0, 0.94);
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 16px;
	}

	.preview-back img {
		max-width: 100%;
		max-height: 88vh;
		border-radius: 14px;
		object-fit: contain;
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);
	}

	.preview-close {
		position: absolute;
		top: 16px;
		right: 16px;
		background: rgba(255, 255, 255, 0.15);
		border: none;
		border-radius: 50%;
		width: 44px;
		height: 44px;
		color: #fff;
		font-size: 20px;
		backdrop-filter: blur(8px);
	}

	/* ── Edit modal ── */
	.edit-warga {
		display: flex;
		align-items: center;
		gap: 10px;
		background: var(--c-bg);
		border-radius: 12px;
		padding: 12px 14px;
		margin-bottom: 20px;
	}

	.ew-badge {
		width: 40px;
		height: 40px;
		border-radius: 10px;
		background: var(--c-primary);
		color: #fff;
		display: flex;
		align-items: center;
		justify-content: center;
		font-weight: 800;
		font-size: 14px;
		flex-shrink: 0;
	}

	.ew-mid {
		flex: 1;
		min-width: 0;
	}

	.ew-name {
		font-size: 14px;
		font-weight: 700;
	}

	.ew-sub {
		font-size: 12px;
		color: var(--c-text-muted);
	}

	.status-pills {
		display: flex;
		gap: 8px;
		margin-top: 6px;
	}

	.s-pill {
		flex: 1;
		padding: 10px 6px;
		background: var(--c-surface);
		border: 1.5px solid var(--c-border);
		border-radius: 12px;
		color: var(--c-text-muted);
		font-size: 11px;
		font-weight: 700;
		font-family: inherit;
		text-align: center;
		line-height: 1.2;
	}

	.s-pill.on {
		background: var(--c-primary-soft);
		border-color: var(--c-primary);
		color: var(--c-primary-dark);
	}

	.opt {
		font-weight: 400;
		color: var(--c-text-light);
	}

	.modal-actions {
		display: flex;
		gap: 10px;
	}

	.modal-actions .btn {
		flex: 1;
		height: 46px;
	}
</style>

// client/src/pages/LaporanWarga.jsx
import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { pb } from '../lib/pocketbase';
// ── Toast untuk notifikasi mobile-native ──
function Toast({ message, type, onClose }) {
  useEffect(() => {
    const t = setTimeout(onClose, 2800);
    return () => clearTimeout(t);
  }, [onClose]);
  const bg = type === 'success' ? '#15935A' : type === 'error' ? '#C24A4A' : '#1B211E';
  return (
    <div style={{
      position: 'fixed', bottom: 96, left: '50%', transform: 'translateX(-50%)',
      zIndex: 99999, background: bg, color: '#fff',
      padding: '14px 24px', borderRadius: 14, fontSize: 14, fontWeight: 600,
      boxShadow: '0 8px 32px rgba(0,0,0,0.25)',
      maxWidth: 360, width: 'calc(100% - 40px)',
      textAlign: 'center', animation: 'fadeIn 0.2s ease',
      backdropFilter: 'blur(8px)',
    }}>
      {message}
    </div>
  );
}

// ── Stat Card ──
function StatCard({ label, count, color, bg }) {
  return (
    <div style={{
      flex: 1, background: bg || '#F0F4F1', borderRadius: 14,
      padding: '12px 10px', textAlign: 'center',
    }}>
      <div style={{ fontSize: 22, fontWeight: 800, color: color || '#15935A', lineHeight: 1.2 }}>{count}</div>
      <div style={{ fontSize: 11, fontWeight: 600, color: '#6B7B72', marginTop: 2 }}>{label}</div>
    </div>
  );
}

// ── Status Badge ──
function StatusBadge({ status }) {
  const conf = {
    'Selesai':      { bg: '#E8F5EE', color: '#15935A', icon: '✓' },
    'Diproses':     { bg: '#FBF1DD', color: '#C8821A', icon: '⟳' },
    'Ditolak':      { bg: '#FBE9E9', color: '#C24A4A', icon: '✕' },
  };
  const s = conf[status] || { bg: '#EEF1EF', color: '#8A9991', icon: '○' };
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: 5,
      padding: '4px 10px', borderRadius: 20,
      fontSize: 11, fontWeight: 700,
      background: s.bg, color: s.color,
    }}>
      <span style={{ fontSize: 13, lineHeight: 1 }}>{s.icon}</span>
      {status || 'Menunggu'}
    </span>
  );
}

export default function LaporanWarga() {
  const navigate = useNavigate();
  const [laporanList, setLaporanList] = useState([]);
  const [previewImage, setPreviewImage] = useState(null);
  const [isPengurus, setIsPengurus] = useState(() => localStorage.getItem('isPengurus') === 'true');
  const [currentWarga, setCurrentWarga] = useState(null);

  // Scurity tidak boleh mengakses halaman ini
  const isScurity = localStorage.getItem('isScurity') === 'true';
  useEffect(() => {
    if (isScurity) navigate('/dashboard', { replace: true });
  }, [isScurity, navigate]);

  // Edit modal state
  const [editModal, setEditModal] = useState(null); // item object or null
  const [editStatus, setEditStatus] = useState('');
  const [editRespons, setEditRespons] = useState('');
  const [saving, setSaving] = useState(false);

  // Toast state
  const [toast, setToast] = useState(null);
  const textareaRef = useRef(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        // Ambil data warga yang login untuk cek kepemilikan laporan
        const userId = pb.authStore.model?.id;
        let myWarga = null;
        if (userId) {
          try {
            myWarga = await pb.collection('warga').getFirstListItem(`user="${userId}"`);
            setCurrentWarga(myWarga);
            if (myWarga.pengurus) {
              setIsPengurus(true);
            }
          } catch (e) {
            console.warn("Warga not found:", e);
          }
        }

        const records = await pb.collection('lapor').getFullList({
          expand: 'warga,warga.user',
          sort: '-created',
        });

        // Filter client-side: jika bukan pengurus, sembunyikan laporan "Menunggu Konfirmasi"
        // yang bukan miliknya (lapisan keamanan tambahan selain backend rule)
        let filtered = records;
        if (myWarga && !myWarga.pengurus) {
          filtered = records.filter(item => {
            // Tampilkan jika status bukan "Menunggu Konfirmasi"
            if (item.status !== 'Menunggu Konfirmasi') return true;
            // Tampilkan jika laporan milik warga yang sedang login
            if (item.warga === myWarga.id) return true;
            return false;
          });
        }

        setLaporanList(filtered);
      } catch (e) {
        console.warn("Error fetching data:", e);
      }
    };
    if (pb.authStore.isValid) fetchData();
  }, []);

  const handleUpdateReport = async () => {
    if (!editModal) return;
    setSaving(true);
    try {
      const record = await pb.collection('lapor').update(editModal.id, {
        status: editStatus,
        respons: editRespons,
      });
      setLaporanList(prev => prev.map(item =>
        item.id === editModal.id ? { ...item, ...record } : item
      ));
      setEditModal(null);
      setToast({ message: 'Laporan berhasil diperbarui ✓', type: 'success' });
    } catch (err) {
      console.error("Failed to update report:", err);
      setToast({ message: 'Gagal memperbarui laporan.', type: 'error' });
    } finally {
      setSaving(false);
    }
  };

  const openEdit = (item) => {
    setEditModal(item);
    setEditStatus(item.status || 'Menunggu Konfirmasi');
    setEditRespons(item.respons || '');
    setTimeout(() => textareaRef.current?.focus(), 350);
  };

  // ── Hitung statistik ──
  const stats = {
    total: laporanList.length,
    selesai: laporanList.filter(l => l.status === 'Selesai').length,
    proses: laporanList.filter(l => l.status === 'Diproses' || !l.status || l.status === 'Menunggu Konfirmasi').length,
  };

  return (
    <div className="page-padded" style={{ paddingBottom: 'calc(var(--nav-height) + 16px)' }}>
      {/* Header */}
      <div className="header-green">
        <div className="header-row">
          <div>
            <div style={{ color: 'rgba(255,255,255,.7)', fontSize: 14, fontWeight: 500 }}>Warga P2S</div>
            <div style={{ color: '#fff', fontSize: 20, fontWeight: 800, letterSpacing: '-0.02em' }}>Laporan Warga</div>
          </div>
          <button
            onClick={() => navigate(-1)}
            style={{
              background: 'rgba(255,255,255,0.15)',
              border: '1px solid rgba(255,255,255,0.2)',
              color: '#fff', padding: '8px 16px',
              borderRadius: 20, fontSize: 13, fontWeight: 600,
              cursor: 'pointer', minHeight: 44,
              backdropFilter: 'blur(4px)',
              WebkitBackdropFilter: 'blur(4px)',
            }}
          >
            ← Kembali
          </button>
        </div>
      </div>

      <div className="page-content" style={{ marginTop: -24 }}>
        {/* Stats row */}
        {laporanList.length > 0 && (
          <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
            <StatCard label="Total" count={stats.total} color="#1B211E" bg="#EFF1F0" />
            <StatCard label="Selesai" count={stats.selesai} color="#15935A" bg="#E8F5EE" />
            <StatCard label="Diproses" count={stats.proses} color="#C8821A" bg="#FBF1DD" />
          </div>
        )}

        {/* Info banner untuk warga biasa */}
        {!isPengurus && laporanList.length > 0 && (
          <div style={{
            display: 'flex', alignItems: 'center', gap: 8,
            background: '#FBF1DD', borderRadius: 12,
            padding: '10px 14px', marginBottom: 16,
            fontSize: 12, color: '#7A5A14', lineHeight: 1.4,
          }}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" style={{flexShrink: 0}}>
              <circle cx="12" cy="12" r="9" stroke="#C8821A" strokeWidth="1.8"/>
              <path d="M12 7v6" stroke="#C8821A" strokeWidth="1.8" strokeLinecap="round"/>
              <circle cx="12" cy="16" r="1" fill="#C8821A"/>
            </svg>
            <span>Laporan menunggu konfirmasi hanya terlihat oleh pengurus dan pelapor.</span>
          </div>
        )}

        {/* List */}
        <div className="flex-col" style={{ gap: 12 }}>
          {laporanList.length === 0 ? (
            <div style={{
              display: 'flex', flexDirection: 'column', alignItems: 'center',
              gap: 12, padding: '48px 20px', color: '#8A9991', textAlign: 'center',
            }}>
              <div style={{
                width: 64, height: 64, borderRadius: 20,
                background: '#EFF1F0', display: 'flex',
                alignItems: 'center', justifyContent: 'center',
                fontSize: 28, marginBottom: 4,
              }}>📋</div>
              <div style={{ fontSize: 16, fontWeight: 700, color: '#1B211E' }}>
                Belum Ada Laporan
              </div>
              <div style={{ fontSize: 13, lineHeight: 1.5, maxWidth: 260 }}>
                {isPengurus ? 'Warga belum mengirim laporan apapun. Laporan akan muncul di sini.' : 'Belum ada laporan yang tersedia. Laporan menunggu konfirmasi tidak ditampilkan.'}
              </div>
            </div>
          ) : (
            laporanList.map(item => (
              <div
                key={item.id}
                className="card"
                style={{
                  padding: 16,
                  borderLeft: item.status === 'Selesai'
                    ? '4px solid #15935A'
                    : item.status === 'Ditolak'
                    ? '4px solid #C24A4A'
                    : '4px solid #C8821A',
                }}
              >
                <div style={{ display: 'flex', gap: 12 }}>
                  {/* Foto */}
                  {item.foto && (
                    <img
                      src={`/api/files/${item.collectionId}/${item.id}/${item.foto}?thumb=160x160`}
                      alt="Laporan"
                      loading="lazy"
                      style={{
                        width: 72, height: 72, objectFit: 'cover', borderRadius: 12,
                        cursor: 'pointer', flexShrink: 0,
                        border: '1px solid #EFF1F0',
                      }}
                      onClick={() => setPreviewImage(
                        `/api/files/${item.collectionId}/${item.id}/${item.foto}`
                      )}
                    />
                  )}
                  <div style={{ flex: 1, minWidth: 0 }}>
                    {/* Header info */}
                    <div style={{
                      fontSize: 13, fontWeight: 700, color: '#1B211E', marginBottom: 2,
                      display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap',
                    }}>
                      <span>{item.expand?.warga?.expand?.user?.name || 'Warga'}</span>
                      <span style={{ color: '#8A9991', fontWeight: 500 }}>
                        · No. {item.expand?.warga?.no_rumah}
                      </span>
                    </div>

                    {/* Keterangan */}
                    <p style={{
                      fontSize: 13, color: '#475569', lineHeight: 1.45,
                      marginBottom: 8, display: '-webkit-box',
                      WebkitLineClamp: 3, WebkitBoxOrient: 'vertical',
                      overflow: 'hidden',
                    }}>
                      {item.keterangan}
                    </p>

                    {/* Status + date row */}
                    <div style={{
                      display: 'flex', justifyContent: 'space-between',
                      alignItems: 'center', gap: 8, flexWrap: 'wrap',
                    }}>
                      <StatusBadge status={item.status} />
                      <span style={{ fontSize: 11, color: '#8A9991', whiteSpace: 'nowrap' }}>
                        {item.created ? new Date(item.created).toLocaleDateString('id-ID', {
                          day: 'numeric', month: 'short', year: 'numeric'
                        }) : '—'}
                      </span>
                    </div>

                    {/* Respons pengurus */}
                    {item.respons && (
                      <div style={{
                        marginTop: 10, padding: '10px 12px',
                        background: '#F8FAFC', borderRadius: 10,
                        borderLeft: '3px solid #15935A',
                      }}>
                        <div style={{
                          fontSize: 10, fontWeight: 700, color: '#15935A',
                          marginBottom: 3, textTransform: 'uppercase',
                          letterSpacing: '0.04em',
                        }}>
                          Tanggapan Pengurus
                        </div>
                        <div style={{ fontSize: 12, color: '#475569', lineHeight: 1.45 }}>
                          {item.respons}
                        </div>
                      </div>
                    )}

                    {/* Tombol Edit (pengurus only) */}
                    {isPengurus && (
                      <button
                        onClick={() => openEdit(item)}
                        style={{
                          marginTop: 10, padding: '8px 14px',
                          background: '#EFF1F0', color: '#1B211E',
                          border: 'none', borderRadius: 10,
                          fontSize: 12, fontWeight: 700, cursor: 'pointer',
                          minHeight: 40, display: 'inline-flex',
                          alignItems: 'center', gap: 6,
                          transition: 'background 0.15s',
                        }}
                        onPointerDown={e => e.currentTarget.style.background = '#E2E8F0'}
                        onPointerUp={e => e.currentTarget.style.background = '#EFF1F0'}
                        onPointerLeave={e => e.currentTarget.style.background = '#EFF1F0'}
                      >
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                          <path d="M10 1.5L12.5 4L4.5 12H2V9.5L10 1.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                        Edit / Tanggapi
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* ── FULL-SCREEN IMAGE PREVIEW ── */}
      {previewImage && (
        <div
          onClick={() => setPreviewImage(null)}
          style={{
            position: 'fixed', inset: 0, zIndex: 9999,
            background: 'rgba(0,0,0,0.94)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            padding: 16,
            animation: 'fadeIn 0.15s ease',
          }}
        >
          <button
            onClick={() => setPreviewImage(null)}
            aria-label="Tutup"
            style={{
              position: 'absolute', top: 16, right: 16,
              background: 'rgba(255,255,255,0.15)',
              border: 'none', borderRadius: '50%',
              width: 48, height: 48, minHeight: 48,
              color: '#fff', fontSize: 20,
              cursor: 'pointer', display: 'flex',
              alignItems: 'center', justifyContent: 'center',
              zIndex: 10000, backdropFilter: 'blur(8px)',
              WebkitBackdropFilter: 'blur(8px)',
            }}
          >
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path d="M4 4L16 16M16 4L4 16" stroke="#fff" strokeWidth="2" strokeLinecap="round"/>
            </svg>
          </button>
          <img
            src={previewImage}
            alt="Preview Laporan"
            onClick={e => e.stopPropagation()}
            style={{
              maxWidth: '100%', maxHeight: '88vh', borderRadius: 14,
              objectFit: 'contain', boxShadow: '0 20px 60px rgba(0,0,0,0.5)',
            }}
          />
        </div>
      )}

      {/* ── BOTTOM SHEET EDIT MODAL ── */}
      {editModal && (
        <div className="modal-backdrop" onClick={() => !saving && setEditModal(null)}>
          <div
            className="modal-content"
            onClick={e => e.stopPropagation()}
            style={{
              maxHeight: '70vh',
              animation: 'slideUp 0.25s cubic-bezier(0.32, 0.72, 0, 1)',
            }}
          >
            <div className="modal-header">
              <h3 style={{ fontSize: 17, fontWeight: 800 }}>Edit Laporan</h3>
              <button
                className="close-btn"
                onClick={() => setEditModal(null)}
                disabled={saving}
                style={{ minHeight: 44, minWidth: 44 }}
              >
                ✕
              </button>
            </div>

            <div className="modal-body" style={{ padding: '20px 20px 8px' }}>
              {/* Info warga */}
              <div style={{
                background: '#F4F6F4', borderRadius: 12, padding: '12px 14px',
                marginBottom: 20, display: 'flex', alignItems: 'center', gap: 10,
              }}>
                <div style={{
                  width: 40, height: 40, borderRadius: 10,
                  background: '#15935A', color: '#fff',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontWeight: 800, fontSize: 14, flexShrink: 0,
                }}>
                  {editModal.expand?.warga?.no_rumah?.slice(-2) || '?'}
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: 14, fontWeight: 700, color: '#1B211E' }}>
                    {editModal.expand?.warga?.expand?.user?.name || 'Warga'}
                  </div>
                  <div style={{ fontSize: 12, color: '#6B7B72' }}>
                    No. {editModal.expand?.warga?.no_rumah}
                  </div>
                </div>
                <StatusBadge status={editModal.status} />
              </div>

              {/* Status selector */}
              <div style={{ marginBottom: 20 }}>
                <label style={{
                  fontSize: 12, fontWeight: 700, color: '#475569',
                  display: 'block', marginBottom: 8,
                }}>
                  Status Laporan
                </label>
                <div style={{ display: 'flex', gap: 8 }}>
                  {['Menunggu Konfirmasi', 'Diproses', 'Selesai', 'Ditolak'].map(s => (
                    <button
                      key={s}
                      onClick={() => setEditStatus(s)}
                      style={{
                        flex: 1, padding: '10px 6px', minHeight: 44,
                        border: editStatus === s ? '2px solid #15935A' : '1.5px solid #E6EBE7',
                        borderRadius: 12, background: editStatus === s ? '#E8F5EE' : '#fff',
                        color: editStatus === s ? '#15935A' : '#6B7B72',
                        fontSize: 11, fontWeight: 700, cursor: 'pointer',
                        fontFamily: 'inherit', textAlign: 'center',
                        transition: 'all 0.15s', lineHeight: 1.2,
                      }}
                    >
                      {s === 'Menunggu Konfirmasi' ? 'Menunggu' : s}
                    </button>
                  ))}
                </div>
              </div>

              {/* Textarea tanggapan */}
              <div style={{ marginBottom: 12 }}>
                <label style={{
                  fontSize: 12, fontWeight: 700, color: '#475569',
                  display: 'block', marginBottom: 8,
                }}>
                  Tanggapan <span style={{ fontWeight: 400, color: '#8A9991' }}>(opsional)</span>
                </label>
                <textarea
                  ref={textareaRef}
                  value={editRespons}
                  onChange={e => setEditRespons(e.target.value)}
                  placeholder="Tulis tanggapan untuk warga..."
                  rows={3}
                  style={{
                    width: '100%', padding: '12px 14px', minHeight: 80,
                    borderRadius: 12, border: '1.5px solid #E6EBE7',
                    fontSize: 15, fontFamily: 'inherit', color: '#1B211E',
                    background: '#fff', resize: 'none',
                    lineHeight: 1.5,
                    transition: 'border-color 0.15s',
                  }}
                  onFocus={e => e.target.style.borderColor = '#15935A'}
                  onBlur={e => e.target.style.borderColor = '#E6EBE7'}
                />
              </div>
            </div>

            {/* Footer */}
            <div className="modal-footer" style={{
              display: 'flex', gap: 10, padding: '12px 20px',
              paddingBottom: 'calc(env(safe-area-inset-bottom, 12px) + 12px)',
            }}>
              <button
                onClick={() => setEditModal(null)}
                disabled={saving}
                className="btn"
                style={{
                  flex: 1, background: '#F0F2F0', color: '#475569',
                  border: 'none', borderRadius: 14, fontSize: 15,
                  fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit',
                  minHeight: 50,
                }}
              >
                Batal
              </button>
              <button
                onClick={handleUpdateReport}
                disabled={saving}
                className="btn btn-primary"
                style={{
                  flex: 1.5, borderRadius: 14, fontSize: 15,
                  fontWeight: 700, minHeight: 50,
                  opacity: saving ? 0.6 : 1,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  gap: 8,
                }}
              >
                {saving ? (
                  <>
                    <span style={{
                      width: 18, height: 18, borderRadius: '50%',
                      border: '2.5px solid rgba(255,255,255,0.3)',
                      borderTopColor: '#fff',
                      animation: 'spin 0.6s linear infinite',
                      display: 'inline-block',
                    }} />
                    Menyimpan...
                  </>
                ) : (
                  'Simpan Perubahan'
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── TOAST ── */}
      {toast && (
        <Toast
          message={toast.message}
          type={toast.type}
          onClose={() => setToast(null)}
        />
      )}

      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
        @keyframes slideUp { from { transform: translateY(100%); } to { transform: translateY(0); } }
      `}</style>

    </div>
  );
}
