// client/src/pages/Mutasi.jsx
import { useState, useEffect } from 'react';
import { pb, API_URL } from '../lib/pocketbase';

export default function Mutasi() {
  const [isPengurus, setIsPengurus] = useState(() => localStorage.getItem('isPengurus') === 'true');
  const [fileList, setFileList] = useState([]);
  const [selectedFile, setSelectedFile] = useState(null);
  const [mutasiList, setMutasiList] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [uploadMsg, setUploadMsg] = useState(null);
  const [uploadError, setUploadError] = useState(null);
  const [showUpload, setShowUpload] = useState(false);
  const [bulanInput, setBulanInput] = useState(() => {
    const d = new Date();
    return `${String(d.getMonth() + 1).padStart(2, '0')}-${d.getFullYear()}`;
  });

  const rupiah = (n) => { let v = n || 0; if (v < 1 && v > 0) v = 0; return 'Rp ' + v.toLocaleString('id-ID'); };

  useEffect(() => {
    const fetchFiles = async () => {
      setLoading(true);
      try {
        const userId = pb.authStore.model.id;
        const warga = await pb.collection('warga').getFirstListItem(`user="${userId}"`);
        const isPengurusDb = warga.pengurus || false;
        setIsPengurus(isPengurusDb);
        localStorage.setItem('isPengurus', isPengurusDb ? 'true' : 'false');

        const records = await pb.collection('file_mutasi').getFullList({
          sort: '-created',
          expand: 'uploaded_by'
        });
        records.sort((a, b) => new Date(b.created) - new Date(a.created));
        setFileList(records);

        if (records.length > 0) {
          setSelectedFile(records[0]);
        }
      } catch (e) {
        console.warn('Error fetching file mutasi:', e);
      }
      setLoading(false);
    };

    if (pb.authStore.isValid) fetchFiles();
  }, []);

  useEffect(() => {
    const fetchMutasi = async () => {
      if (!selectedFile) { setMutasiList([]); return; }
      setLoadingDetail(true);
      try {
        const records = await pb.collection('mutasi').getFullList({
          filter: `file_mutasi="${selectedFile.id}"`,
          sort: 'no_urut'
        });
        setMutasiList(records);
      } catch (e) {
        console.warn('Error fetching mutasi:', e);
        setMutasiList([]);
      }
      setLoadingDetail(false);
    };
    if (pb.authStore.isValid && selectedFile) fetchMutasi();
  }, [selectedFile]);

  const getFileUrl = (record) => {
    if (!record.file_pdf) return null;
    return `/api/files/${record.collectionId}/${record.id}/${record.file_pdf}`;
  };

  const handleUpload = async (e) => {
    e.preventDefault();
    const fileInput = e.target.file_pdf;
    if (!fileInput.files || fileInput.files.length === 0) {
      setUploadError('Pilih file PDF dulu');
      return;
    }
    const file = fileInput.files[0];
    const password = e.target.password?.value || '08111992';

    setUploading(true);
    setUploadMsg(null);
    setUploadError(null);
    try {
      const formData = new FormData();
      formData.append('file_pdf', file);
      formData.append('password', password);
      formData.append('bulan', bulanInput);

      const token = pb.authStore.token;
      const resp = await fetch(`${API_URL}/v1/mutasi/upload`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
        body: formData,
      });
      const result = await resp.json();
      if (!resp.ok) {
        throw new Error(result.message || 'Upload gagal');
      }
      setUploadMsg(`✅ ${result.message} — ${result.jumlah_transaksi} transaksi (bulan ${result.bulan})`);
      setShowUpload(false);
      e.target.reset();

      // Refresh data
      const records = await pb.collection('file_mutasi').getFullList({ sort: '-created' });
      records.sort((a, b) => new Date(b.created) - new Date(a.created));
      setFileList(records);
      if (records.length > 0) {
        setSelectedFile(records[0]);
      }
    } catch (err) {
      console.error(err);
      setUploadError(err.message || 'Upload gagal');
    }
    setUploading(false);
  };

  return (
    <div className="page-padded" style={{ paddingBottom: 40 }}>
      <div style={{ padding: '16px 20px 0', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <h2 style={{ margin: 0 }}>Mutasi Rekening</h2>
          <p style={{ margin: '4px 0 0', color: '#6B7B72', fontSize: 12 }}>Data mutasi dari file PDF yang diupload</p>
        </div>
        {isPengurus && (
          <button
            onClick={() => setShowUpload(!showUpload)}
            style={{
              background: '#15935A', color: '#fff', border: 'none', borderRadius: 12,
              padding: '10px 16px', fontSize: 13, fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit'
            }}
          >
            {showUpload ? 'Tutup' : '+ Upload'}
          </button>
        )}
      </div>

      {/* Upload form (hanya pengurus) */}
      {isPengurus && showUpload && (
        <form onSubmit={handleUpload} className="card" style={{ margin: '16px 20px 0', padding: 16 }}>
          <h4 style={{ margin: '0 0 12px', fontSize: 14 }}>📄 Upload Mutasi PDF</h4>
          <input
            type="file" name="file_pdf" accept="application/pdf"
            style={{ width: '100%', padding: 8, border: '1.5px solid #E6EBE7', borderRadius: 10, fontSize: 12, marginBottom: 10 }}
            required
          />
          <input
            type="text" name="password" placeholder="Password PDF (default 08111992)"
            defaultValue="08111992"
            style={{ width: '100%', padding: 10, border: '1.5px solid #E6EBE7', borderRadius: 10, fontSize: 12, marginBottom: 10 }}
          />
          <label style={{ fontSize: 11, color: '#6B7B72', fontWeight: 600 }}>Bulan (format MM-YYYY)</label>
          <input
            type="text" name="bulan" value={bulanInput}
            onChange={(e) => setBulanInput(e.target.value)}
            placeholder="contoh: 08-2026"
            pattern="\d{2}-\d{4}"
            maxLength="7"
            style={{ width: '100%', padding: 10, border: '1.5px solid #E6EBE7', borderRadius: 10, fontSize: 12, margin: '4px 0 10px', fontFamily: 'inherit' }}
          />
          <button
            type="submit" disabled={uploading}
            style={{
              width: '100%', background: uploading ? '#A8C9B8' : '#15935A', color: '#fff',
              border: 'none', borderRadius: 10, padding: '11px', fontSize: 13, fontWeight: 700,
              cursor: uploading ? 'default' : 'pointer', fontFamily: 'inherit'
            }}
          >
            {uploading ? 'Mengupload & Parse...' : 'Upload & Parse'}
          </button>
          {uploadMsg && <div style={{ marginTop: 10, fontSize: 12, color: '#15935A', fontWeight: 600 }}>{uploadMsg}</div>}
          {uploadError && <div style={{ marginTop: 10, fontSize: 12, color: '#C24A4A', fontWeight: 600 }}>❌ {uploadError}</div>}
        </form>
      )}

      {/* Summary cards */}
      {selectedFile && (
        <div style={{ margin: '16px 20px 0', background: 'linear-gradient(145deg, #147a4a, #0C6B40)', borderRadius: 16, padding: 18, color: '#fff' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <div style={{ fontSize: 12, opacity: 0.85, fontWeight: 600 }}>📄 {selectedFile.nama_file}</div>
              <div style={{ fontSize: 11, opacity: 0.7, marginTop: 2 }}>
                {selectedFile.bulan ? `Bulan ${selectedFile.bulan}` : ''}
                {selectedFile.periode_awal ? ` · ${new Date(selectedFile.periode_awal).toLocaleDateString('id-ID', { day: 'numeric', month: 'short' })}` : ''}
                {selectedFile.periode_akhir ? ` — ${new Date(selectedFile.periode_akhir).toLocaleDateString('id-ID', { day: 'numeric', month: 'short' })}` : ''}
              </div>
            </div>
            {selectedFile.file_pdf && (
              <a href={getFileUrl(selectedFile)} target="_blank" rel="noreferrer" style={{ background: 'rgba(255,255,255,0.2)', padding: '8px 12px', borderRadius: 10, fontSize: 11, color: '#fff', textDecoration: 'none', fontWeight: 700 }}>
                📥 PDF
              </a>
            )}
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginTop: 12 }}>
            <div style={{ background: 'rgba(255,255,255,0.1)', borderRadius: 10, padding: 8 }}>
              <div style={{ fontSize: 10, opacity: 0.7 }}>Saldo Awal</div>
              <div style={{ fontSize: 15, fontWeight: 700 }}>{rupiah(selectedFile.saldo_awal)}</div>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.1)', borderRadius: 10, padding: 8 }}>
              <div style={{ fontSize: 10, opacity: 0.7 }}>Saldo Akhir</div>
              <div style={{ fontSize: 15, fontWeight: 700 }}>{rupiah(selectedFile.saldo_akhir)}</div>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.1)', borderRadius: 10, padding: 8 }}>
              <div style={{ fontSize: 10, opacity: 0.7 }}>Total Masuk</div>
              <div style={{ fontSize: 13, fontWeight: 700 }}>{rupiah(selectedFile.total_kredit)}</div>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.1)', borderRadius: 10, padding: 8 }}>
              <div style={{ fontSize: 10, opacity: 0.7 }}>Total Keluar</div>
              <div style={{ fontSize: 13, fontWeight: 700 }}>{rupiah(selectedFile.total_debet)}</div>
            </div>
          </div>
        </div>
      )}

      {/* File list selector */}
      <div style={{ display: 'flex', gap: 8, marginTop: 20, padding: '0 20px', overflowX: 'auto', paddingBottom: 4 }}>
        {fileList.map((f) => (
          <button key={f.id} onClick={() => setSelectedFile(f)}
            style={{
              flex: 'none', border: selectedFile?.id === f.id ? '1.5px solid #15935A' : '1.5px solid #E6EBE7',
              background: selectedFile?.id === f.id ? '#E8F5EE' : '#fff',
              color: selectedFile?.id === f.id ? '#15935A' : '#6B7B72',
              padding: '8px 14px', borderRadius: 20, fontSize: 11, fontWeight: selectedFile?.id === f.id ? 700 : 600,
              cursor: 'pointer', fontFamily: 'inherit', whiteSpace: 'nowrap',
            }}
          >{f.bulan || f.nama_file}</button>
        ))}
        {fileList.length === 0 && <span style={{ color: '#8A9991', fontSize: 12 }}>Belum ada file mutasi</span>}
      </div>

      {/* Mutation detail table */}
      <div style={{ marginTop: 16, padding: '0 20px' }}>
        {loading || loadingDetail ? (
          <div style={{ textAlign: 'center', padding: 40, color: '#8A9991', fontSize: 14 }}>Memuat...</div>
        ) : mutasiList.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 40, color: '#8A9991', fontSize: 14 }}>
            <div style={{ fontSize: 48, opacity: 0.3, marginBottom: 10 }}>📭</div>
            Belum ada data mutasi — upload PDF dulu ya
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11, minWidth: 600 }}>
              <thead>
                <tr style={{ background: '#F5FAF7', color: '#0F1A14' }}>
                  <th style={{ padding: '8px 6px', textAlign: 'center', borderBottom: '1px solid #E6EBE7', fontWeight: 700 }}>No</th>
                  <th style={{ padding: '8px 6px', textAlign: 'left', borderBottom: '1px solid #E6EBE7', fontWeight: 700 }}>Tanggal</th>
                  <th style={{ padding: '8px 6px', textAlign: 'left', borderBottom: '1px solid #E6EBE7', fontWeight: 700 }}>Keterangan</th>
                  <th style={{ padding: '8px 6px', textAlign: 'right', borderBottom: '1px solid #E6EBE7', fontWeight: 700 }}>Debet</th>
                  <th style={{ padding: '8px 6px', textAlign: 'right', borderBottom: '1px solid #E6EBE7', fontWeight: 700 }}>Kredit</th>
                  <th style={{ padding: '8px 6px', textAlign: 'right', borderBottom: '1px solid #E6EBE7', fontWeight: 700 }}>Saldo</th>
                </tr>
              </thead>
              <tbody>
                {mutasiList.map((m) => (
                  <tr key={m.id} style={{ borderBottom: '1px solid #F0F3F1' }}>
                    <td style={{ padding: '7px 6px', textAlign: 'center', color: '#6B7B72' }}>{m.no_urut}</td>
                    <td style={{ padding: '7px 6px', whiteSpace: 'nowrap' }}>
                      {m.tanggal_posting ? new Date(m.tanggal_posting).toLocaleDateString('id-ID', { day: '2-digit', month: 'short' }) : '-'}
                    </td>
                    <td style={{ padding: '7px 6px', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: '#0F1A14' }}>
                      {m.keterangan}
                    </td>
                    <td style={{ padding: '7px 6px', textAlign: 'right', color: '#C24A4A', whiteSpace: 'nowrap' }}>
                      {m.mutasi_debet ? rupiah(m.mutasi_debet) : '-'}
                    </td>
                    <td style={{ padding: '7px 6px', textAlign: 'right', color: '#15935A', whiteSpace: 'nowrap' }}>
                      {m.mutasi_kredit ? rupiah(m.mutasi_kredit) : '-'}
                    </td>
                    <td style={{ padding: '7px 6px', textAlign: 'right', fontWeight: 600, whiteSpace: 'nowrap' }}>
                      {rupiah(m.saldo_akhir)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

// client-v2/src/routes/mutasi/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { pb } from '$lib/pb';
	import { isPengurus } from '$lib/auth';
	import { fmtRupiah, toast } from '$lib/ui';
	import type { FileMutasi, MutasiRow } from '$lib/types';
	import {
		listFileMutasi,
		listMutasiRows,
		fileMutasiUrl,
		uploadFileMutasi
	} from '$lib/mutasi';
	import States from '$lib/components/States.svelte';

	let files = $state<FileMutasi[]>([]);
	let selected = $state<FileMutasi | null>(null);
	let rows = $state<MutasiRow[]>([]);
	let loading = $state(true);
	let loadingDetail = $state(false);
	let error = $state('');
	let showUpload = $state(false);
	let uploading = $state(false);

	// Upload form
	let uploadFile = $state<File | null>(null);
	let password = $state('08111992');
	let bulan = $state(defaultBulan());

	function defaultBulan(): string {
		const d = new Date();
		return `${String(d.getMonth() + 1).padStart(2, '0')}-${d.getFullYear()}`;
	}

	async function loadFiles(preserveSelectedId?: string) {
		loading = true;
		error = '';
		try {
			files = await listFileMutasi();
			if (files.length > 0) {
				if (preserveSelectedId) {
					selected = files.find((f) => f.id === preserveSelectedId) ?? files[0];
				} else {
					selected = files[0];
				}
			} else {
				selected = null;
			}
		} catch (e) {
			error = e instanceof Error ? e.message : 'Gagal memuat file mutasi.';
		} finally {
			loading = false;
		}
	}

	async function loadRows(fileId: string) {
		loadingDetail = true;
		try {
			rows = await listMutasiRows(fileId);
		} catch (e) {
			console.warn('rows fetch:', e);
			rows = [];
		} finally {
			loadingDetail = false;
		}
	}

	onMount(() => {
		if (pb.authStore.isValid) void loadFiles();
	});

	$effect(() => {
		if (selected) void loadRows(selected.id);
		else rows = [];
	});

	function onFilePicked(e: Event) {
		const input = e.currentTarget as HTMLInputElement;
		uploadFile = input.files?.[0] ?? null;
	}

	async function submitUpload(e: Event) {
		e.preventDefault();
		if (!uploadFile) {
			toast('Pilih file PDF dulu', 'err');
			return;
		}
		uploading = true;
		try {
			const res = await uploadFileMutasi(uploadFile, password, bulan);
			toast(
				`${res.message ?? 'Upload sukses'} — ${res.jumlah_transaksi ?? 0} transaksi (bulan ${res.bulan ?? bulan})`,
				'ok'
			);
			showUpload = false;
			uploadFile = null;
			await loadFiles();
		} catch (err) {
			toast(err instanceof Error ? err.message : 'Upload gagal.', 'err');
		} finally {
			uploading = false;
		}
	}

	function fmtTanggal(v?: string): string {
		if (!v) return '-';
		return new Date(v).toLocaleDateString('id-ID', {
			day: '2-digit',
			month: 'short'
		});
	}

	function fmtPeriode(f: FileMutasi): string {
		const parts: string[] = [];
		if (f.bulan) parts.push(`Bulan ${f.bulan}`);
		if (f.periode_awal)
			parts.push(fmtTanggal(f.periode_awal));
		if (f.periode_akhir)
			parts[parts.length - 1] += ` — ${fmtTanggal(f.periode_akhir)}`;
		return parts.filter(Boolean).join(' · ');
	}
</script>

<div class="page">
	<div class="head">
		<div>
			<h1>Mutasi Rekening</h1>
			<p>Data mutasi dari file PDF yang diupload</p>
		</div>
		{#if $isPengurus}
			<button class="btn-upload" onclick={() => (showUpload = !showUpload)}>
				{showUpload ? 'Tutup' : '+ Upload'}
			</button>
		{/if}
	</div>

	<!-- Form upload -->
	{#if $isPengurus && showUpload}
		<form class="card upload-form" onsubmit={submitUpload}>
			<h4>📄 Upload Mutasi PDF</h4>
			<label class="f-label" for="mutasi-file">File PDF</label>
			<input
				id="mutasi-file"
				type="file"
				accept="application/pdf"
				onchange={onFilePicked}
				required
				class="mini-input"
			/>
			<label class="f-label" for="mutasi-pass">Password PDF</label>
			<input
				id="mutasi-pass"
				type="text"
				bind:value={password}
				placeholder="08111992"
				class="mini-input"
			/>
			<label class="f-label" for="mutasi-bulan">Bulan (MM-YYYY)</label>
			<input
				id="mutasi-bulan"
				type="text"
				bind:value={bulan}
				pattern="\d{'{'}2{'}'}-\d{'{'}4{'}'}"
				maxlength="7"
				placeholder="08-2026"
				class="mini-input"
			/>
			<button class="btn btn-primary" type="submit" disabled={uploading}>
				{uploading ? 'Mengupload & Parse…' : 'Upload & Parse'}
			</button>
		</form>
	{/if}

	<!-- Summary card file terpilih -->
	{#if selected}
		<div class="summary">
			<div class="s-head">
				<div>
					<div class="s-name">📄 {selected.nama_file || '(tanpa nama)'}</div>
					<div class="s-period">{fmtPeriode(selected)}</div>
				</div>
				{#if selected.file_pdf}
					<a
						class="s-pdf"
						href={fileMutasiUrl(selected)}
						target="_blank"
						rel="noreferrer"
					>
						📥 PDF
					</a>
				{/if}
			</div>
			<div class="s-grid">
				<div class="s-cell">
					<div class="k">Saldo Awal</div>
					<div class="v">{fmtRupiah(selected.saldo_awal)}</div>
				</div>
				<div class="s-cell">
					<div class="k">Saldo Akhir</div>
					<div class="v">{fmtRupiah(selected.saldo_akhir)}</div>
				</div>
				<div class="s-cell">
					<div class="k">Total Masuk</div>
					<div class="v small">{fmtRupiah(selected.total_kredit)}</div>
				</div>
				<div class="s-cell">
					<div class="k">Total Keluar</div>
					<div class="v small">{fmtRupiah(selected.total_debet)}</div>
				</div>
			</div>
		</div>
	{/if}

	<!-- File selector -->
	{#if files.length > 0}
		<div class="pills">
			{#each files as f (f.id)}
				<button
					class="pill"
					class:on={selected?.id === f.id}
					onclick={() => (selected = f)}
				>
					{f.bulan || f.nama_file}
				</button>
			{/each}
		</div>
	{/if}

	<!-- Table -->
	<div class="table-wrap">
		{#if loading || loadingDetail}
			<States kind="loading" rows={6} />
		{:else if error}
			<States kind="error" text={error} onRetry={() => loadFiles()} />
		{:else if !selected}
			<States kind="empty" title="Belum ada file mutasi" text="Upload PDF dulu ya." />
		{:else if rows.length === 0}
			<States
				kind="empty"
				title="Belum ada data mutasi"
				text="Upload PDF di halaman ini."
			/>
		{:else}
			<div class="scroll">
				<table class="tbl">
					<thead>
						<tr>
							<th class="c">No</th>
							<th>Tanggal</th>
							<th>Keterangan</th>
							<th class="r">Debet</th>
							<th class="r">Kredit</th>
							<th class="r">Saldo</th>
						</tr>
					</thead>
					<tbody>
						{#each rows as m (m.id)}
							<tr>
								<td class="c muted">{m.no_urut}</td>
								<td class="nw">{fmtTanggal(m.tanggal_posting)}</td>
								<td class="trunc">{m.keterangan || '-'}</td>
								<td class="r out">{m.mutasi_debet ? fmtRupiah(m.mutasi_debet) : '-'}</td>
								<td class="r in">{m.mutasi_kredit ? fmtRupiah(m.mutasi_kredit) : '-'}</td>
								<td class="r bal">{fmtRupiah(m.saldo_akhir)}</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		{/if}
	</div>
</div>

<style>
	.page {
		padding: 16px 20px 40px;
	}

	.head {
		display: flex;
		align-items: flex-start;
		justify-content: space-between;
		gap: 12px;
		margin-bottom: 16px;
	}

	.head h1 {
		font-size: 18px;
		font-weight: 800;
		letter-spacing: -0.02em;
	}

	.head p {
		font-size: 12px;
		color: var(--c-text-muted);
		margin-top: 4px;
	}

	.btn-upload {
		background: var(--c-primary);
		color: #fff;
		border: none;
		border-radius: 12px;
		padding: 10px 16px;
		font-size: 13px;
		font-weight: 700;
		font-family: inherit;
	}

	.upload-form {
		padding: 16px;
		margin-bottom: 16px;
	}

	.upload-form h4 {
		font-size: 14px;
		font-weight: 800;
		margin-bottom: 12px;
	}

	.mini-input {
		width: 100%;
		padding: 10px;
		border: 1.5px solid var(--c-border);
		border-radius: 10px;
		font-size: 12px;
		font-family: inherit;
		background: var(--c-surface);
		margin-bottom: 10px;
	}

	.upload-form .btn {
		margin-top: 4px;
		height: 44px;
	}

	.summary {
		background: linear-gradient(145deg, #147a4a, #0c6b40);
		border-radius: 16px;
		padding: 18px;
		color: #fff;
		margin-bottom: 16px;
	}

	.s-head {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
		gap: 10px;
	}

	.s-name {
		font-size: 12px;
		font-weight: 600;
		opacity: 0.9;
	}

	.s-period {
		font-size: 11px;
		opacity: 0.7;
		margin-top: 2px;
	}

	.s-pdf {
		background: rgba(255, 255, 255, 0.2);
		padding: 8px 12px;
		border-radius: 10px;
		font-size: 11px;
		color: #fff;
		text-decoration: none;
		font-weight: 700;
		white-space: nowrap;
	}

	.s-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 10px;
		margin-top: 12px;
	}

	.s-cell {
		background: rgba(255, 255, 255, 0.1);
		border-radius: 10px;
		padding: 8px 10px;
	}

	.s-cell .k {
		font-size: 10px;
		opacity: 0.7;
	}

	.s-cell .v {
		font-size: 15px;
		font-weight: 700;
		font-family: var(--mono);
		margin-top: 2px;
	}

	.s-cell .v.small {
		font-size: 13px;
	}

	.pills {
		display: flex;
		gap: 8px;
		overflow-x: auto;
		padding-bottom: 4px;
		margin-bottom: 12px;
		scrollbar-width: none;
	}

	.pills::-webkit-scrollbar {
		display: none;
	}

	.pill {
		flex: none;
		background: var(--c-surface);
		border: 1.5px solid var(--c-border);
		color: var(--c-text-muted);
		padding: 8px 14px;
		border-radius: 20px;
		font-size: 11px;
		font-weight: 600;
		font-family: inherit;
		white-space: nowrap;
	}

	.pill.on {
		background: var(--c-primary-soft);
		border-color: var(--c-primary);
		color: var(--c-primary-dark);
		font-weight: 700;
	}

	.table-wrap {
		margin-top: 4px;
	}

	.scroll {
		overflow-x: auto;
	}

	.tbl {
		width: 100%;
		border-collapse: collapse;
		font-size: 11px;
		min-width: 600px;
	}

	.tbl thead tr {
		background: #f5faf7;
	}

	.tbl th {
		padding: 8px 6px;
		font-weight: 700;
		color: var(--c-text);
		border-bottom: 1px solid var(--c-border);
		text-align: left;
	}

	.tbl td {
		padding: 7px 6px;
		border-bottom: 1px solid var(--c-border-light);
		vertical-align: middle;
	}

	.tbl .c {
		text-align: center;
	}

	.tbl .r {
		text-align: right;
	}

	.tbl .nw {
		white-space: nowrap;
	}

	.tbl .muted {
		color: var(--c-text-muted);
	}

	.tbl .trunc {
		max-width: 200px;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.tbl .out {
		color: var(--c-red);
		white-space: nowrap;
	}

	.tbl .in {
		color: var(--c-primary);
		white-space: nowrap;
	}

	.tbl .bal {
		font-weight: 700;
		white-space: nowrap;
	}
</style>
